### ISSUE TITLE
Wired layout behavior maybe caused by release 1.5.2

### ISSUE THREAD

**Issue by wjling** [mirego/PinLayout#118]
If use PinLayout, scrolling tableView will be relayout repeatedly and acts wired. Using frame will be fine. I have an issue demo here:  https://github.com/wjling/PinTestDemo1

Since update to 1.5.6，I found many issues in my app except I mentioned above😭, not only transform. I think these layout issues have something to do with 1.5.2 or 1.5.3. Maybe PinLayout changes its mechanism about seting frame or bounds

**Comment by lucdion** [comment]
Hi @wjling, sorry for all that issues, since I have change the way PinLayout update view's frame (https://github.com/mirego/PinLayout/releases/tag/1.5.2), this change have impacted few details that were not covered by unit tests, this was particularly affection UIScrollView/UITableView. This has all been fixed in the release 1.5.7 and 1.5.8.

If you update your project to the latest release 1.5.8, everything works fine, I've tested your sample.

Thanks for using PinLayout, and don't hesitate to report any issues 🙂

**Comment by wjling** [comment]
Glad to hear that you fix these issues! PinLayout is a convenient layout tool!

**Comment by wjling** [comment]
Hi @lucdion . I want to share my thoughts about the release 1.5.2, only about the transform. I think this release make PinLayout a bit different with manual layout when we apply transforms. If we apply a rotation in a view, we can't use PinLayout to layout its final frame. We should calculate view's layout before we apply rotation, then we use PinLayout. If a view has been rotated, we can't use PinLayout to apply something like `top()`, `marginLeft(3)`. Because these `top()`, `margin` is relative to the status that the view hasn't been transformed. But previous release can. Finally I think PinLayout doesn't do well when there are transforms. It is my feedback after experiencing the changes in 1.5.2. What do you think about my problem?

**Comment by lucdion** [comment]
Hi @wjling, thanks for sharing your tought. Could you share me a sample of your problem?
If I understand correctly, you have a view with a rotated transform, and you'd like to pin it at the top. Your view is non-square?
First think I want to understand correctly the issue, then we could think of different solutions to configure how PinLayout apply layout to its view that contains a transform.

But it could help me a lot if you could just share me a little piece of code that expose this situation.

Thanks

**Comment by wjling** [comment]
Hi @lucdion .Maybe some pictures can help to explain myself. Sorry about the poor painting😅.
I have picture in a imageView (the red border one):
![911518008279_ pic](https://user-images.githubusercontent.com/4201777/35918160-c0085bf4-0c4b-11e8-8a27-09fbd84e4836.jpg)
I perform a 90° rotation on it and I want it to be the same frame, like this:
![931518008546_ pic](https://user-images.githubusercontent.com/4201777/35918264-288b648c-0c4c-11e8-8e82-4a0764550656.jpg)
But PinLayout make it like this:
![941518009274_ pic](https://user-images.githubusercontent.com/4201777/35918299-41fb3fa0-0c4c-11e8-8f2a-c86faedd2927.jpg)

If a view has applied some transformation, I think is hard to use `top()`, `left()` or other constraints to layout it. The reference system has been changed because of transformation. `top()` or `left()` is not performing the way we think about it in current reference system. 

Maybe you can understand what I say. I also update the demo: https://github.com/wjling/PinTestDemo1

**Comment by lucdion** [comment]
Hi @wjling, thanks for the details.

Since release 1.5.2, PinLayout now respect the view's transform and doesn't modify it. So if for example you have applied a rotation transform, PinLayout will adjust the position and the size of the untransformed view.

In your case you want to update the position/size of the rotated view. But suppose you would like to obtain the PinLayout's result, i.e. keep the rotation transform but change the position and the size of the view, you wouldn't be able by setting the `frame` property. 

This is in fact **two different scenarios**. I think it requires a mechanism to specify which one we want to use.

I propose to keep's PinLayout current behaviour (I think its easier for animations), but  adds a `pinFrame` property to really apply the new position/size to the view's frame. 

In your example it would replace:
```
  tableView.pin.top(80).left().right().height(100)
```

By:
```
  tableView.pinFrame.top(80).left().right().height(100)
```

I'm not sure yet about the name `pinFrame`.

Comments?

**Comment by wjling** [comment]
Yes, there is two different scenarios. I am in such scenario that I should operate a lot of animations in a view. In this scenario using manual layout maybe less calculation and more understandable than PinLayout. 

If we can choose which way of Pin to use in different scenarios could be a nice solution. It will make PinLayout more flexible

**Comment by lucdion** [comment]
Hi @wjling, the following release (https://github.com/mirego/PinLayout/releases/tag/1.5.9) add a `pinFrame` property.

https://github.com/mirego/PinLayout#uiviews-transforms
