### ISSUE TITLE
SafeArea Question

### ISSUE THREAD

**Issue by Michael-Davies** [mirego/PinLayout#140]
Thanks for such a great library guys! I have a quick question to the `pin.safeArea` lifecycle. I'm replacing my entire view within my viewcontroller but I'm running into some issues with the safe area.

```
override func loadView() {
        let view = SignupPage1View()
        view.delegate = self
        self.view = view
}

func changeView() {
        let view = SignupPage2View()
        view.delegate = self
        self.view = view
}
```

The view is being replaced successfully but the safe areas don't match up anymore. The first view successfully sits correctly under the navigation, but the second view appears below instead. I'm wondering do I need to call something to recalculate the safe areas?

**Comment by lucdion** [comment]
Interesting case @Michael-Davies, I will investigate that.

**Comment by antoinelamy** [comment]
One thing is for sure, UIViewController is not designed for it's managing view to be swapped at runtime like that. Internally, UIViewController register as a private delegate to it's view shortly after `loadView` to receive callbacks about it's lifecycle events such as `viewDidLayoutSubviews`. By swapping the view itself, the view controller do not get called anymore when it's view layout is performed. Safe areas for older iOS versions than iOS 11 get computed in `viewDidLayoutSubviews` so I assume it is normal that you don't get the correct safeArea for your newly created view.

The way to go would be to replace a subview of your view controller's view instead of the root view itself and calling `view.setNeedsLayout()` when that occur, that should fix your problem.

**Comment by lucdion** [comment]
Thanks @antoinelamy for the answer, there is no real overhead of adding subviews and its much cleaner and respect the purpose of the `UIViewController.loadView()` method.
