### ISSUE TITLE
Performance benchmarks

### ISSUE THREAD

**Issue by cliren** [mirego/PinLayout#31]
The API is very intuitive and can't wait to try this in our projects. One of the core requirement for us is performance, curious to know if there are any performance benchmarks similar to https://engineering.linkedin.com/blog/2016/06/open-sourcing-layoutkit--a-fast-view-layout-library-for-ios-appl?

**Comment by lucmirego** [comment]
Hi @cliren, thanks for your comment. I totally agree that it would be very good to have performance comparison. It is at the top of my TODO list, but didn't have the time yet to do that. 

It would be particularly useful to have a standard test than can be used to compare all layouting frameworks.

PinLayout don't compute view's size implicitly using sizeThatFits() or similar methods, except  when explicitly specified by the developer using the `PinLayout.sizeToFit()` method. This is one of the biggest auto layout performance issues, including also the management of all constraints and their priorities.

PinLayout doesn't perform many calculations, it's complexity is really low. It is mainly function calls.

So for these reasons I'm pretty confident that the performance won't be an issue, but since I don't have any stats to prove that, I can't be sure.

How do you check if a layout framework is performant? Are you testing them internally? Have you any test to validate that? If that's the case, I would be very interested to implement these tests using PinLayout.

**Comment by lucmirego** [comment]
Hi @cliren, LayoutKit's benchmark is available in their sample app. I've forked the repo and I have added PinLayout. The result is amazing! 😄  The PinLayout code is smaller and really nice, and the performance is even faster than their Manual Layout implementation. Their manual layout implementation was calling too often sizeToFit() on views that size didn't change.

I'll document that on the project README.

Here are the graph for UICollectionView
![screen shot 2017-06-07 at 2 53 48 pm](https://user-images.githubusercontent.com/14981341/26895971-5479d5e6-4b91-11e7-91c1-524223e6d22f.png)
. 
Here is the forked LayoutKit and the PinLayout implementation of their benchmark: https://github.com/mirego/LayoutKit/blob/update_benchmark_to_include_PinLayout/LayoutKitSampleApp/Benchmarks/FeedItemPinLayoutView.swift

**Comment by lucmirego** [comment]
If you're interrested, here is the Excel document containing the data. Test were done on a iPhone 7 iOS 10.3.2.

[LayoutKit-Benchmark-with-PinLayout.xlsx](https://github.com/mirego/PinLayout/files/1059020/LayoutKit-Benchmark-with-PinLayout.xlsx)

**Comment by cliren** [comment]
cool, thanks for checking that!

**Comment by lucmirego** [comment]
Performance results has been added to the documentation. Thanks
