### ISSUE TITLE
AL Anchors Integration

### ISSUE THREAD

**Issue by bolismauro** [mirego/PinLayout#68]
Hi!
First of all, great project! 

I was wondering if there is a way to integrate PinLayout with some of the UIView's property like `topAnchor` or the upcoming `safeAreaLayoutGuide`. Juts having a way to get the x,y of that anchors should be good enough

Any idea?
Thanks!

**Comment by lucdion** [comment]
Hi @bolismauro, 

You should use `UIView.safeAreaInsets` instead of `UIView.safeAreaLayoutGuide`. See https://developer.apple.com/documentation/uikit/uiview/2891103-safeareainsets

`UIView.safeAreaInsets` is a great improvement over `topLayoutGuide` and `bottomLayoutGuide` which were available only on UIViewController.

You can use the same technique I use in our sample app to handle `topLayoutGuide` (see for example https://github.com/mirego/PinLayout/blob/master/Example/PinLayoutSample/UI/Tests/MultiRelativeView/MultiRelativeView.swift). 

Instead of using `topLayoutGuide`, you can use directly `UIView.safeAreaInsets`. 

Example:
```
    view1.pin.top(safeAreaInsets.top).left().width(20%).height(50%)
```

**Comment by bolismauro** [comment]
I didn't know about `safeAreaInsets`. Amazing, that's exactly what I was looking for :)

**Comment by lucdion** [comment]
@bolismauro, if you like the project thanks to Star it 🙂
Also, you may be interested by my other project called FlexLayout which wrap Yoga flexbox implementation. It is not released yet, but it is fully functional. It integrates nicely with PinLayout. https://github.com/lucdion/FlexLayout/tree/dev
