### ISSUE TITLE
Print line and file of conflict

### ISSUE THREAD

**Issue by dunqi** [mirego/PinLayout#74]
Hello,

it's difficulty to debug layout issues, if PinLayout is not printing the name of the view or the line of code. Could you add this feature? Thank you

**Comment by lucdion** [comment]
Hi @dunqi,
It is not possible to print out the view instance name, the file and the line number due to the PinLayout protocol. But what would be possible is to display more context. 

For example, it could print:
* The class name of the view being layouted.
* The view's current frame
* The class name of all the view superviews  
* The view's Tag

Something like that:
👉 PinLayout Warning: width(-20.0) won't be applied, the width (-20.0) must be greater than or equal to zero.
   (View type: ItemButton, Frame: (140.0, 100.0, 100.0, 60.0), Superviews: HomeView -> UIView, Tag: 0)

**Comment by dunqi** [comment]
Yes, that would help debugging too

**Comment by lucdion** [comment]
@dunqi a new release 1.2.3 which improve warnings is available: https://github.com/mirego/PinLayout/releases/tag/1.2.3
Thanks for your input!
